# New ports collection makefile for:	ocaml-xstr
# Date created:		2006-07-29
# Whom:			Stanislav Sedov <ssedov@mbsd.msk.ru>
#
# $MBSDlabs$
# $FreeBSD: ports/devel/ocaml-xstr/Makefile,v 1.6 2011/10/24 03:32:57 stas Exp $
#

PORTNAME=	xstr
PORTVERSION=	0.2.1
PORTREVISION=	2
CATEGORIES=	devel
MASTER_SITES=	http://www.ocaml-programming.de/packages/
PKGNAMEPREFIX=	ocaml-

MAINTAINER=	ports@FreeBSD.org
COMMENT=	Thread-safe implementation of string searching/matching

WRKSRC=		${WRKDIR}/${PORTNAME}
USE_GMAKE=	yes
USE_OCAML=	yes
USE_OCAML_FINDLIB=yes

.include <bsd.port.mk>
